<div class="link">
	<h3>Liên kết thư viện</h3>
	<div class="link bar" style="">
		<a href=""><p class="ncbsearch">Search 01</p></a>
	</div>
	<div class="link bar" style="">
		<a href=""><p class="ncbsearch">Search 02</p></a>
	</div>
	<div class="link bar" style="">
		<a href=""><p class="ncbsearch">Search 03</p></a>
	</div>
	<div class="link bar" style="">
		<a href=""><p class="ncbsearch">Search 03</p></a>
	</div>
</div>